name: HtmlToPdfRpi release

on:
  release:
    types: [published]

jobs:
  build_release_arm32v7:
    name: Build release-arm32v7
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet publish
      working-directory: src
      run: dotnet publish -c Release -o ../build/arm32v7/out -r linux-arm /p:Version=${GITHUB_REF#refs/tags/} HtmlToPdfRpi

    - name: Create docker image
      uses: uraimo/run-on-arch-action@v2.0.5
      with:
        arch: arvmv7
        distro: ubuntu18.04
        working-directory: build/arm32v7
        run: docker build -t ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/}-arm32v7 .
    
    - name: Push docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/}-arm32v7
